# Generated by Django 4.2 on 2023-08-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_profile_bio_profile_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                default="profiles/avatar.svg", upload_to="profiles"
            ),
        ),
    ]
