# Generated by Django 4.2 on 2023-07-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_brand_colorvariation_sizevariation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(auto_created=True, unique=True),
        ),
    ]
