# Generated by Django 4.2 on 2023-08-20 15:58

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_product_options_product_rate_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="id",
        ),
        migrations.AddField(
            model_name="review",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="updated",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="value",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")],
                max_length=1,
            ),
        ),
    ]
