# Generated by Django 4.2 on 2023-08-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_remove_review_id_review_uid_review_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="overall_rate",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
