# Generated by Django 4.2 on 2023-07-24 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_slug"),
        ("order", "0003_rename_name_order_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="color_varient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.colorvariation",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size_varient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.sizevariation",
            ),
        ),
    ]
