# Generated by Django 4.2 on 2023-07-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0011_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="discount_price",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="minimum_amount",
            field=models.PositiveIntegerField(default=500),
        ),
    ]
