# Generated by Django 4.2 on 2023-08-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0014_cart_razorpay_order_id_cart_razorpay_payment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Order Placed", "Order Placed"),
                    ("Order Confirmed", "Order Confirmed"),
                    ("Dispatched", "Dispatched"),
                    ("Shipped", "Shipped"),
                    ("Out for Delivery", "Out for Delivery"),
                    ("Delivered", "Delivered"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
