# Generated by Django 4.2 on 2023-08-17 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0016_remove_order_status_orderitem_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="order.order"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Order Placed", "Order Placed"),
                    ("Order Confirmed", "Order Confirmed"),
                    ("Dispatched", "Dispatched"),
                    ("Shipped", "Shipped"),
                    ("Out for Delivery", "Out for Delivery"),
                    ("Delivered", "Delivered"),
                    ("Cancled", "Cancled"),
                    ("Return", "Return"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
