# Generated by Django 4.2 on 2023-08-18 14:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_slug"),
        ("order", "0017_alter_orderitem_order_alter_orderitem_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="status",
        ),
        migrations.CreateModel(
            name="OrderItemHistory",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                ("quantity", models.IntegerField(blank=True, default=1, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Order Placed", "Order Placed"),
                            ("Order Confirmed", "Order Confirmed"),
                            ("Dispatched", "Dispatched"),
                            ("Shipped", "Shipped"),
                            ("Out for Delivery", "Out for Delivery"),
                            ("Delivered", "Delivered"),
                            ("Cancled", "Cancled"),
                            ("Return", "Return"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "color_varient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product.colorvariation",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="order.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product.product",
                    ),
                ),
                (
                    "size_varient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product.sizevariation",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("order", "product", "size_varient", "color_varient")
                },
            },
        ),
    ]
