# Generated by Django 4.2 on 2023-08-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0019_alter_orderitemhistory_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitemhistory",
            name="item_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
